# meta cell class --------------------------------------------------------------

## s7 object -------------------------------------------------------------------

#' @title bixverse meta cell class
#'
#' @description
#' This is the `bixverse`-based meta cell class. It is generated by running
#' meta-cell generating functions on top of the main class. Due to the
#' aggregation of the count matrices to a way smaller number of meta cells,
#' the data is held in memory for this class specifically. Additional methods
#' that make specific usage of meta cells (especially co-expression module
#' detection ones will be made available).
#'
#' @param meta_cell_data Named list. Output of meta-cell generation Rust
#' functions. Will contain the aggregated raw and normalised counts, plus
#' additional information on the origin of the meta cells.
#' @param var_data data.table with the variable/feature informations.
#' @param meta_cell_method String describing the origin of the metacell.
#'
#' @section Properties:
#' \describe{
#'   \item{obs_table}{The meta cell observation table.}
#'   \item{var_table}{The meta cell variable table.}
#'   \item{data}{List with the raw and normalised counts.}
#'   \item{sc_cache}{Class with embeddings, kNN/sNN graphs, etc. Shared with
#'   [bixverse::SingleCells()].}
#'   \item{original_assignment}{List with original assignment information.}
#'   \item{dims}{Dimensions of the new meta cell matrices.}
#'   \item{other_data}{Potential other data returned from the meta-cell
#'   generating methods.}
#' }
#'
#' @return Returns the `MetaCells` class for further operations.
#'
#' @export
MetaCells <- S7::new_class(
  name = "MetaCells",
  properties = list(
    obs_table = S7::class_data.frame,
    var_table = S7::class_data.frame,
    data = S7::class_list,
    sc_cache = S7::class_any,
    original_assignment = S7::class_list,
    dims = S7::class_integer,
    other_data = S7::class_list,
    meta_cell_method = S7::class_character
  ),
  constructor = function(meta_cell_data, var_data, meta_cell_method) {
    # checks
    checkmate::assertList(meta_cell_data)
    checkmate::assertNames(
      names(meta_cell_data),
      must.include = c("aggregated", "assignments")
    )
    checkmate::assertDataTable(var_data)
    checkmate::assertNames(
      names(var_data),
      must.include = c("gene_idx", "gene_id")
    )
    checkmate::qassert(meta_cell_method, "S1")

    # function body
    n_digits <- nchar(as.character(meta_cell_data$assignments$n_metacells))
    format_str <- sprintf("meta_cell_%%0%dd", n_digits)

    obs_data <- data.table::data.table(
      meta_cell_idx = 1:meta_cell_data$assignments$n_metacells,
      meta_cell_id = sprintf(
        format_str,
        1:meta_cell_data$assignments$n_metacells
      ),
      no_originating_cells = purrr::map_dbl(
        meta_cell_data$assignments$metacells,
        length
      ),
      original_cell_idx = meta_cell_data$assignments$metacells
    )

    c(raw_counts, norm_counts) %<-%
      get_meta_cell_matrices(meta_cell_data$aggregated)

    rownames(raw_counts) <- rownames(norm_counts) <- obs_data$meta_cell_id
    colnames(raw_counts) <- colnames(norm_counts) <- var_data$gene_id

    other_data <- if (meta_cell_method == "seacell") {
      list(
        rss = meta_cell_data$rss,
        archetypes = meta_cell_data$archetypes
      )
    } else {
      list()
    }

    ## can't use the helper function, S7 requires new_object()
    obj <- S7::new_object(
      S7::S7_object(),
      obs_table = obs_data,
      var_table = var_data,
      data = list(raw = raw_counts, norm = norm_counts),
      sc_cache = new_sc_cache(),
      original_assignment = meta_cell_data$assignments[c(
        "assignments",
        "n_cells",
        "n_metacells",
        "n_unassigned"
      )],
      dims = as.integer(c(nrow(raw_counts), ncol(norm_counts))),
      other_data = other_data,
      meta_cell_method = meta_cell_method
    )
  }
)

#' Merging of MetaCell objects
#'
#' A named list of `MetaCells` objects can be provided. `MetaCells`
#' objects will be merged by concatenating the counts and obs table.
#' The meta_cell_id is renamed using the names of the list.
#'
#' @param x List. Named list of `MetaCells` objects to merge
#' @param feature_space String. How do deal with different set of features
#' across samples, can be either using the "intersect" or the "union".
#' (Default: "union")
#'
#' @rdname merge
#'
#' @export
merge.MetaCells <- function(
  x,
  feature_space = c("union")
) {
  # --- Input validation ---
  checkmate::assertList(x, types = "bixverse::MetaCells", min.len = 2)
  checkmate::assertNamed(x, type = "unique")
  checkmate::assertChoice(feature_space, choices = c("union", "intersect"))

  # Ensure all objects used the same metacell method
  methods <- vapply(x, function(obj) obj@meta_cell_method, character(1))
  if (length(unique(methods)) > 1) {
    stop(sprintf(
      "All MetaCells objects must use the same meta_cell_method. Found: %s",
      paste(unique(methods), collapse = ", ")
    ))
  }
  meta_cell_method <- methods[[1]]

  # --- Merge obs_table ---
  ## re-index the merged obs table
  idx_offset <- 0L
  ot_list <- list()
  for (s in names(x)) {
    ot <- x[[s]]@obs_table
    original_max <- max(ot$meta_cell_idx)

    ot$meta_cell_idx_original <- ot$meta_cell_idx
    ot$meta_cell_idx <- ot$meta_cell_idx + idx_offset
    ot$meta_cell_id <- paste0(s, "_", ot$meta_cell_id)

    ot_list[[s]] <- ot
    idx_offset <- idx_offset + original_max
  }
  merged_obs_table <- data.table::rbindlist(ot_list)

  # --- Determine common feature space ---
  set_fn <- if (feature_space == "union") union else intersect
  all_genes <- lapply(x, function(obj) colnames(obj@data$raw))
  common_genes <- sort(Reduce(set_fn, all_genes))

  if (length(common_genes) == 0) {
    stop(
      "No common genes found across MetaCells objects after applying feature_space = '",
      feature_space,
      "'."
    )
  }

  # --- Merge raw counts ---
  ## need to reindex
  merged_raw_counts <- Reduce(
    MatrixExtra::rbind_csr,
    lapply(names(x), function(s) {
      m <- x[[s]]@data$raw
      rownames(m) <- paste0(s, "_", rownames(m))
      as(as(m, "CsparseMatrix")[, common_genes, drop = FALSE], "RsparseMatrix")
    })
  )

  # --- Merge norm counts ---
  ## need to reindex
  merged_norm_counts <- Reduce(
    MatrixExtra::rbind_csr,
    lapply(names(x), function(s) {
      m <- x[[s]]@data$norm
      rownames(m) <- paste0(s, "_", rownames(m))
      as(as(m, "CsparseMatrix")[, common_genes, drop = FALSE], "RsparseMatrix")
    })
  )

  # --- Merge var_table ---
  merged_var_table <- unique(data.table::rbindlist(
    lapply(x, function(obj) obj@var_table),
    fill = TRUE
  ))
  merged_var_table <- merged_var_table[
    match(gene_id, colnames(merged_raw_counts)),
  ] %>%
    .[, gene_idx := .I]

  # --- Merge original_assignment ---
  original_assignment_merged <- list(
    assignments = do.call(
      c,
      lapply(x, function(obj) obj@original_assignment$assignments)
    ),
    n_cells = do.call(
      sum,
      lapply(x, function(obj) obj@original_assignment$n_cells)
    ),
    n_metacells = do.call(
      sum,
      lapply(x, function(obj) obj@original_assignment$n_metacells)
    ),
    n_unassigned = do.call(
      sum,
      lapply(x, function(obj) obj@original_assignment$n_unassigned)
    )
  )

  # --- Merge other_data (seacell only) ---
  other_data <- if (meta_cell_method == "seacell") {
    list(
      rss = lapply(x, function(obj) obj@other_data$rss),
      archetypes = lapply(x, function(obj) obj@other_data$archetypes)
    )
  } else {
    list()
  }

  # --- Construct merged MetaCells object ---
  obj <- .create_MetaCells_obj(
    obs_table = merged_obs_table,
    var_table = merged_var_table,
    data = list(raw = merged_raw_counts, norm = merged_norm_counts),
    sc_cache = new_sc_cache(),
    original_assignment = original_assignment_merged,
    dims = as.integer(c(nrow(merged_raw_counts), ncol(merged_norm_counts))),
    other_data = other_data,
    meta_cell_method = meta_cell_method
  )
  return(obj)
}

# Internal helper — calls new_object() from within its own constructor context
.create_MetaCells_obj <- S7::new_class(
  name = "MetaCells", # same name = same class
  parent = MetaCells,
  constructor = function(
    obs_table,
    var_table,
    data,
    sc_cache,
    original_assignment,
    dims,
    other_data,
    meta_cell_method
  ) {
    S7::new_object(
      S7::S7_object(),
      obs_table = obs_table,
      var_table = var_table,
      data = data,
      sc_cache = sc_cache,
      original_assignment = original_assignment,
      dims = dims,
      other_data = other_data,
      meta_cell_method = meta_cell_method
    )
  }
)


## primitives ------------------------------------------------------------------

#' @name print.MetaCells
#'
#' @title print Method for MetaCells object
#'
#' @description
#' Print a MetaCells object.
#'
#' @param x An object of class `MetaCells`.
#' @param ... Additional arguments (currently not used).
#'
#' @returns Invisibly returns `x`.
#'
#' @method print MetaCells
#'
#' @keywords internal
S7::method(print, MetaCells) <- function(x, ...) {
  # checks
  checkmate::assertTRUE(S7::S7_inherits(x, MetaCells))

  # various params
  dims <- S7::prop(x, "dims")
  original_assignment <- S7::prop(x, "original_assignment")
  other_data <- S7::prop(x, "other_data")
  sc_cache <- S7::prop(x, "sc_cache")
  meta_cell_method <- S7::prop(x, "meta_cell_method")
  hvg_calculated <- !is.null(other_data[["hvg"]])
  pca_calculated <- !is.null(sc_cache[["pca_factors"]])
  knn_generated <- !is.null(sc_cache[["knn"]])
  snn_generated <- !is.null(sc_cache[["snn_graph"]])
  other_embeddings <- names(sc_cache[["other_embeddings"]])
  other_embeddings_str <- if (length(other_embeddings) > 0) {
    paste(other_embeddings, collapse = ", ")
  } else {
    "none"
  }

  # print
  cat(
    "Single cell experiment (Meta Cells).\n",
    sprintf("  Meta cell method: %s\n", meta_cell_method),
    sprintf("  No meta cells: %i\n", dims[1]),
    sprintf("  No genes: %i\n", dims[2]),
    sprintf("  No original cells: %i\n", original_assignment$n_cells),
    sprintf("  No unassigned cells: %i\n", original_assignment$n_unassigned),
    sprintf("  HVG calculated: %s\n", hvg_calculated),
    sprintf("  PCA calculated: %s\n", pca_calculated),
    sprintf("  Other embeddings: %s\n", other_embeddings_str),
    sprintf("  KNN generated: %s\n", knn_generated),
    sprintf("  SNN generated: %s\n", snn_generated),
    sep = ""
  )
  invisible(x)
}

#' @name head.MetaCells
#'
#' @title head Method for MetaCells object
#'
#' @description
#' Returns the first `n` rows of the obs table from a `MetaCells` object.
#'
#' @param x An object of class `MetaCells`.
#' @param n Integer. Number of rows to return. Defaults to `6L`.
#' @param ... Additional arguments (currently not used).
#'
#' @returns A data.table with the first `n` rows of the obs table.
#'
#' @method head MetaCells
#'
#' @keywords internal
S7::method(head, MetaCells) <- function(x, n = 6L, ...) {
  checkmate::assertTRUE(S7::S7_inherits(x, MetaCells))
  checkmate::qassert(n, "I1[1,)")
  get_sc_obs(x, indices = seq_len(n), filtered = FALSE)
}

## getters ---------------------------------------------------------------------

### obs ------------------------------------------------------------------------

#' @method get_sc_obs MetaCells
#'
#' @export
S7::method(get_sc_obs, MetaCells) <- function(
  object,
  indices = NULL,
  cols = NULL,
  filtered = FALSE
) {
  checkmate::assertClass(object, "bixverse::MetaCells")
  checkmate::qassert(indices, c("0", "I+"))
  checkmate::qassert(filtered, "B1")

  obs_table <- data.table::copy(S7::prop(object, "obs_table"))

  if (!is.null(indices)) {
    obs_table <- obs_table[indices, ]
  }

  if (!is.null(cols)) {
    obs_table <- obs_table[, cols, with = FALSE]
  }

  return(obs_table)
}

#' @method `[[` MetaCells
#'
#' @export
S7::method(`[[`, MetaCells) <- function(x, i, ...) {
  if (missing(i)) {
    i <- NULL
  }
  if (checkmate::qtest(i, "S+")) {
    get_sc_obs(x, cols = i, filtered = FALSE)
  } else if (checkmate::qtest(i, "I+")) {
    get_sc_obs(x, indices = i, filtered = FALSE)
  } else if (checkmate::qtest(i, "0")) {
    get_sc_obs(x, filtered = FALSE)
  } else {
    stop("Invalid type")
  }
}

### vars -----------------------------------------------------------------------

#' @method get_sc_var MetaCells
#'
#' @export
S7::method(get_sc_var, MetaCells) <- function(
  object,
  indices = NULL,
  cols = NULL,
  modality = c("rna", "adt")
) {
  modality <- match.arg(modality)

  checkmate::assertClass(object, "bixverse::MetaCells")
  checkmate::qassert(indices, c("0", "I+"))

  if (modality != "rna") {
    stop(
      paste(
        "MetaCells only supports modality = 'rna'.",
        "Use SingleCellsMultiModal for ADT."
      )
    )
  }

  var_table <- object@var_table

  if (!is.null(indices)) {
    var_table <- var_table[indices, ]
  }

  if (!is.null(cols)) {
    var_table <- var_table[, cols, with = FALSE]
  }

  return(var_table)
}

### counts ---------------------------------------------------------------------

#' @method get_sc_counts MetaCells
#'
#' @export
S7::method(get_sc_counts, MetaCells) <- function(
  object,
  assay = c("raw", "norm"),
  return_format = c("cell", "gene"),
  cell_indices = NULL,
  gene_indices = NULL,
  use_cells_to_keep = TRUE,
  modality = c("rna", "adt"),
  .verbose = TRUE
) {
  checkmate::assertTRUE(S7::S7_inherits(object, MetaCells))
  assay <- match.arg(assay)
  modality <- match.arg(modality)

  if (modality != "rna") {
    stop(
      paste(
        "MetaCells only supports modality = 'rna'.",
        "Use SingleCellsMultiModal for ADT."
      )
    )
  }

  counts <- S7::prop(object, "data")[[assay]]

  if (!is.null(cell_indices)) {
    counts <- counts[cell_indices, , drop = FALSE]
  }

  if (!is.null(gene_indices)) {
    counts <- counts[, gene_indices, drop = FALSE]
  }

  return(counts)
}

#' @method `[` MetaCells
#'
#' @export
S7::method(`[`, MetaCells) <- function(
  x,
  i,
  j,
  ...,
  assay = c("raw", "norm"),
  drop = TRUE
) {
  if (missing(i)) {
    i <- NULL
  }
  if (missing(j)) {
    j <- NULL
  }
  assay <- match.arg(assay)

  # transform (meta)cell ids and gene ids to indices
  if (checkmate::qtest(i, "S+")) {
    i <- get_cell_indices(x = x, cell_ids = i, rust_index = FALSE)
  }
  if (checkmate::qtest(j, "S+")) {
    j <- get_gene_indices(x = x, gene_ids = j, rust_index = FALSE)
  }

  checkmate::qassert(i, c("I+", "0"))
  checkmate::qassert(j, c("I+", "0"))
  checkmate::assertChoice(assay, c("raw", "norm"))

  get_sc_counts(
    object = x,
    assay = assay,
    cell_indices = i,
    gene_indices = j
  )
}

#' Transform the counts to a Rust-specific list
#'
#' @description
#' Helper function to transform the counts from the `MetaCells` into a Rust
#' specific list.
#'
#' @param object `MetaCells` class.
#' @param cell_indices Optional integer. Defines the indices of the (meta)cells
#' to extract.
#' @param gene_indices Optional integer. Defines the indices of the genes to
#' extract.
#' @param assay String. One of `c("raw", "norm")`
#'
#' @keywords internal
#'
#' @export
mc_counts_to_list <- S7::new_generic(
  name = "mc_counts_to_list",
  dispatch_args = "object",
  fun = function(
    object,
    cell_indices = NULL,
    gene_indices = NULL,
    assay = c("raw", "norm")
  ) {
    S7::S7_dispatch()
  }
)

#' @method mc_counts_to_list MetaCells
#'
#' @export
S7::method(mc_counts_to_list, MetaCells) <- function(
  object,
  cell_indices = NULL,
  gene_indices = NULL,
  assay = c("raw", "norm")
) {
  assay <- match.arg(assay)
  # checks
  checkmate::assertChoice(assay, c("raw", "norm"))
  checkmate::assertTRUE(S7::S7_inherits(object, MetaCells))

  # body
  x <- object[cell_indices, gene_indices, assay = assay]

  list(
    indptr = x@p,
    indices = x@j,
    data = x@x,
    format = "csr",
    nrow = nrow(x),
    ncol = ncol(x)
  )
}

#' Get the offsets for the CLR/PFlogPF transformation prior PCA
#'
#' @description
#' Helper function to get the offsets for the CLR/PFlogPF transformation.
#'
#' @param object `MetaCells` class.
#' @param cell_indices Optional integer. Defines the indices of the (meta)cells
#' to use for the calculation.
#'
#' @returns A vector of length cell_indices which contains the CLR offsets
#'
#' @keywords internal
#'
#' @export
mc_get_clr_offsets <- S7::new_generic(
  name = "mc_counts_to_list",
  dispatch_args = "object",
  fun = function(
    object,
    cell_indices = NULL
  ) {
    S7::S7_dispatch()
  }
)

#' @method mc_get_clr_offsets MetaCells
#'
#' @export
S7::method(mc_get_clr_offsets, MetaCells) <- function(
  object,
  cell_indices = NULL
) {
  checkmate::assertTRUE(S7::S7_inherits(object, MetaCells))

  x <- object[cell_indices, , assay = "raw"]

  s <- rowSums(x)
  u <- counts / s
  clr_offsets <- rowMeans(log1p(u))

  clr_offsets
}

## setters ---------------------------------------------------------------------

### obs table ------------------------------------------------------------------

#' @method `[[<-` MetaCells
#'
#' @export
S7::method(`[[<-`, MetaCells) <- function(x, i, ..., value) {
  checkmate::assertClass(x, "bixverse::MetaCells")
  checkmate::qassert(i, "S+")

  if (length(i) == 1) {
    checkmate::qassert(value, "a")
    S7::prop(x, "obs_table")[, (i) := value]
  } else {
    checkmate::assertList(value, names = "named", types = "atomic")
    S7::prop(x, "obs_table")[, (i) := value]
  }

  return(x)
}

### others ---------------------------------------------------------------------

#### setters -------------------------------------------------------------------

#' @name set_hvg.MetaCells
#'
#' @rdname set_hvg
#'
#' @method set_hvg MetaCells
S7::method(set_hvg, MetaCells) <- function(
  x,
  hvg
) {
  # checks
  checkmate::assertTRUE(S7::S7_inherits(x, MetaCells))
  checkmate::qassert(hvg, c("I+", "S+"))

  var_table <- S7::prop(x, "var_table")

  res <- if (is.numeric(hvg)) {
    as.integer(hvg)
  } else {
    idx <- match(hvg, var_table$gene_id)
    missing <- is.na(idx)
    if (any(missing)) {
      warning(sprintf(
        "With the provided hvg gene_ids a total of %i could not be matched.",
        sum(missing)
      ))
      idx <- idx[!missing]
    }
    if (length(idx) == 0) {
      stop(
        "The HVG indices have length 0. Please double check provided parameters!"
      )
    }
    as.integer(idx)
  }

  other_data <- S7::prop(x, "other_data")
  other_data[["hvg"]] <- res
  S7::prop(x, "other_data") <- other_data

  return(x)
}

#### getters -------------------------------------------------------------------

#' @name get_hvg.MetaCells
#'
#' @rdname get_hvg
#'
#' @method get_hvg MetaCells
S7::method(get_hvg, MetaCells) <- function(
  x
) {
  # checks
  checkmate::assertTRUE(S7::S7_inherits(x, MetaCells))

  hvg_indices <- as.integer(S7::prop(x, "other_data")[["hvg"]])
  if (length(hvg_indices) == 0) {
    warning("No highly variable features found in the class.")
  }

  return(hvg_indices)
}

#' @name get_cell_indices.MetaCells
#'
#' @rdname get_cell_indices
#'
#' @method get_cell_indices MetaCells
S7::method(get_cell_indices, MetaCells) <- function(
  x,
  cell_ids,
  rust_index
) {
  # checks
  checkmate::assertTRUE(S7::S7_inherits(x, MetaCells))
  checkmate::qassert(cell_ids, "S+")
  checkmate::qassert(rust_index, "B1")

  indices <- match(cell_ids, x@obs_table[["meta_cell_id"]])

  missing <- is.na(indices)
  if (any(missing)) {
    warning(sprintf(
      "With the provided meta_cell_ids a total of %i could not be matched.",
      sum(missing)
    ))
    indices <- indices[!missing]
  }

  return(indices)
}

#' @name get_gene_indices.MetaCells
#'
#' @rdname get_gene_indices
#'
#' @method get_gene_indices MetaCells
S7::method(get_gene_indices, MetaCells) <- function(
  x,
  gene_ids,
  rust_index
) {
  # checks
  checkmate::assertTRUE(S7::S7_inherits(x, MetaCells))
  checkmate::qassert(gene_ids, "S+")
  checkmate::qassert(rust_index, "B1")

  indices <- match(gene_ids, x@var_table[["gene_id"]])

  missing <- is.na(indices)
  if (any(missing)) {
    warning(sprintf(
      "With the provided gene_ids a total of %i could not be matched.",
      sum(missing)
    ))
    indices <- indices[!missing]
  }

  if (rust_index) {
    indices <- indices - 1L
  }

  if (length(indices) == 0) {
    stop(
      "The gene indices have length 0. Please double check provided parameters!"
    )
  }

  return(indices)
}

### sc cache -------------------------------------------------------------------

#### setters -------------------------------------------------------------------

#' @name set_pca_factors.MetaCells
#'
#' @rdname set_pca_factors
#'
#' @method set_pca_factors MetaCells
S7::method(set_pca_factors, MetaCells) <- function(
  x,
  pca_factor,
  ...
) {
  # checks
  checkmate::assertTRUE(S7::S7_inherits(x, MetaCells))
  checkmate::assertMatrix(pca_factor, mode = "numeric")

  S7::prop(x, "sc_cache") <- set_pca_factors(
    x = S7::prop(x, "sc_cache"),
    pca_factor = pca_factor
  )

  return(x)
}

#' @name set_pca_loadings.MetaCells
#'
#' @rdname set_pca_loadings
#'
#' @method set_pca_loadings MetaCells
S7::method(set_pca_loadings, MetaCells) <- function(
  x,
  pca_loading,
  ...
) {
  # checks
  checkmate::assertTRUE(S7::S7_inherits(x, MetaCells))
  checkmate::assertMatrix(pca_loading, mode = "numeric")

  S7::prop(x, "sc_cache") <- set_pca_loadings(
    x = S7::prop(x, "sc_cache"),
    pca_loading = pca_loading
  )

  return(x)
}

#' @name set_pca_singular_vals.MetaCells
#'
#' @rdname set_pca_singular_vals
#'
#' @method set_pca_singular_vals MetaCells
S7::method(set_pca_singular_vals, MetaCells) <- function(
  x,
  singular_vals,
  ...
) {
  # checks
  checkmate::assertTRUE(S7::S7_inherits(x, MetaCells))
  checkmate::qassert(singular_vals, "N+")

  S7::prop(x, "sc_cache") <- set_pca_singular_vals(
    x = S7::prop(x, "sc_cache"),
    singular_vals = singular_vals
  )

  return(x)
}

#' @name set_embedding.MetaCells
#'
#' @rdname set_embedding
#'
#' @method set_embedding MetaCells
S7::method(set_embedding, MetaCells) <- function(
  x,
  embd,
  name,
  ...
) {
  # checks
  checkmate::assertTRUE(S7::S7_inherits(x, MetaCells))
  checkmate::assertMatrix(embd, mode = "numeric")
  checkmate::qassert(name, "S1")

  S7::prop(x, "sc_cache") <- set_embedding(
    x = S7::prop(x, "sc_cache"),
    embd = embd,
    name = name
  )

  return(x)
}

#' @name set_knn.MetaCells
#'
#' @rdname set_knn
#'
#' @method set_knn MetaCells
S7::method(set_knn, MetaCells) <- function(
  x,
  knn,
  ...
) {
  # checks
  checkmate::assertTRUE(S7::S7_inherits(x, MetaCells))
  checkmate::assertClass(knn, "SingleCellNearestNeighbour")

  S7::prop(x, "sc_cache") <- set_knn(
    x = S7::prop(x, "sc_cache"),
    knn = knn
  )

  return(x)
}

#' @name set_snn_graph.MetaCells
#'
#' @rdname set_snn_graph
#'
#' @method set_snn_graph MetaCells
S7::method(set_snn_graph, MetaCells) <- function(
  x,
  snn_graph,
  ...
) {
  # checks
  checkmate::assertTRUE(S7::S7_inherits(x, MetaCells))
  checkmate::assertClass(snn_graph, "igraph")

  S7::prop(x, "sc_cache") <- set_snn_graph(
    x = S7::prop(x, "sc_cache"),
    snn_graph = snn_graph
  )

  return(x)
}

#' @name remove_knn.MetaCells
#'
#' @rdname remove_knn
#'
#' @method remove_knn MetaCells
S7::method(remove_knn, MetaCells) <- function(
  x,
  ...
) {
  # checks
  checkmate::assertTRUE(S7::S7_inherits(x, MetaCells))

  S7::prop(x, "sc_cache") <- remove_knn(
    x = S7::prop(x, "sc_cache")
  )

  return(x)
}

#' @name remove_snn_graph.MetaCells
#'
#' @rdname remove_snn_graph
#'
#' @method remove_snn_graph MetaCells
S7::method(remove_snn_graph, MetaCells) <- function(
  x,
  ...
) {
  # checks
  checkmate::assertTRUE(S7::S7_inherits(x, MetaCells))

  S7::prop(x, "sc_cache") <- remove_snn_graph(
    x = S7::prop(x, "sc_cache")
  )

  return(x)
}

#### getters -------------------------------------------------------------------

#' @name get_pca_factors.MetaCells
#'
#' @rdname get_pca_factors
#'
#' @method get_pca_factors MetaCells
S7::method(get_pca_factors, MetaCells) <- function(
  x,
  ...
) {
  # checks
  checkmate::assertTRUE(S7::S7_inherits(x, MetaCells))

  res <- get_pca_factors(
    x = S7::prop(x, "sc_cache")
  )

  if (is.null(res)) {
    return(NULL)
  }

  rownames(res) <- S7::prop(x, "obs_table")$meta_cell_id
  colnames(res) <- sprintf("PC_%i", 1:ncol(res))

  return(res)
}

#' @name get_pca_loadings.MetaCells
#'
#' @rdname get_pca_loadings
#'
#' @method get_pca_loadings MetaCells
S7::method(get_pca_loadings, MetaCells) <- function(
  x,
  ...
) {
  # checks
  checkmate::assertTRUE(S7::S7_inherits(x, MetaCells))

  res <- get_pca_loadings(
    x = S7::prop(x, "sc_cache")
  )

  if (is.null(res)) {
    return(NULL)
  }

  colnames(res) <- sprintf("PC_%i", 1:ncol(res))
  rownames(res) <- S7::prop(x, "var_table")$gene_id[get_hvg(x)]

  return(res)
}

#' @name get_pca_singular_val.MetaCells
#'
#' @rdname get_pca_singular_val
#'
#' @method get_pca_singular_val MetaCells
S7::method(get_pca_singular_val, MetaCells) <- function(
  x,
  ...
) {
  # checks
  checkmate::assertTRUE(S7::S7_inherits(x, MetaCells))

  res <- get_pca_singular_val(
    x = S7::prop(x, "sc_cache")
  )

  return(res)
}

#' @name get_embedding.MetaCells
#'
#' @rdname get_embedding
#'
#' @method get_embedding MetaCells
S7::method(get_embedding, MetaCells) <- function(
  x,
  embd_name,
  ...
) {
  # checks
  checkmate::assertTRUE(S7::S7_inherits(x, MetaCells))
  checkmate::qassert(embd_name, "S1")

  res <- get_embedding(
    x = S7::prop(x, "sc_cache"),
    embd_name = embd_name
  )

  rownames(res) <- S7::prop(x, "obs_table")$meta_cell_id

  return(res)
}

#' @name get_available_embeddings.MetaCells
#'
#' @rdname get_available_embeddings
#'
#' @method get_available_embeddings MetaCells
S7::method(get_available_embeddings, MetaCells) <- function(
  x,
  ...
) {
  # checks
  checkmate::assertTRUE(S7::S7_inherits(x, MetaCells))

  res <- get_available_embeddings(
    x = S7::prop(x, "sc_cache")
  )

  return(res)
}

#' @name get_knn_mat.MetaCells
#'
#' @rdname get_knn_mat
#'
#' @method get_knn_mat MetaCells
S7::method(get_knn_mat, MetaCells) <- function(
  x,
  ...
) {
  # checks
  checkmate::assertTRUE(S7::S7_inherits(x, MetaCells))

  res <- get_knn_mat(
    x = S7::prop(x, "sc_cache")
  )

  return(res)
}

#' @name get_knn_dist.MetaCells
#'
#' @rdname get_knn_dist
#'
#' @method get_knn_dist MetaCells
S7::method(get_knn_dist, MetaCells) <- function(
  x,
  ...
) {
  # checks
  checkmate::assertTRUE(S7::S7_inherits(x, MetaCells))

  res <- get_knn_dist(
    x = S7::prop(x, "sc_cache")
  )

  return(res)
}

#' @name get_knn_obj.MetaCells
#'
#' @rdname get_knn_obj
#'
#' @method get_knn_obj MetaCells
S7::method(get_knn_obj, MetaCells) <- function(
  x,
  ...
) {
  # checks
  checkmate::assertTRUE(S7::S7_inherits(x, MetaCells))

  res <- get_knn_obj(
    x = S7::prop(x, "sc_cache")
  )

  return(res)
}

#' @name get_snn_graph.MetaCells
#'
#' @rdname get_snn_graph
#'
#' @method get_snn_graph MetaCells
S7::method(get_snn_graph, MetaCells) <- function(
  x,
  ...
) {
  # checks
  checkmate::assertTRUE(S7::S7_inherits(x, MetaCells))

  res <- get_snn_graph(
    x = S7::prop(x, "sc_cache")
  )

  return(res)
}
