# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_BIXverse_wrappers", use_symbols = TRUE, package_name = "BIXverse")

#' @usage NULL
#' @useDynLib BIXverse, .registration = TRUE
NULL

#' Run a single hypergeometric test.
#' @export
rs_hypergeom_test <- function(target_genes, gene_sets, gene_universe) .Call(wrap__rs_hypergeom_test, target_genes, gene_sets, gene_universe)

#' Run a single hypergeometric test.
#' @export
rs_hypergeom_test_list <- function(target_genes, gene_sets, gene_universe) .Call(wrap__rs_hypergeom_test_list, target_genes, gene_sets, gene_universe)


# nolint end
