# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_BIXverse_wrappers", use_symbols = TRUE, package_name = "BIXverse")

#' @usage NULL
#' @useDynLib BIXverse, .registration = TRUE
NULL

#' Run a single hypergeometric test.
#' 
#' Given a set of target genes, this is a Rust implementation of an hypergeometric test testing for overenrichment
#' of the target genes in the gene sets.
#' 
#' @param target_genes A character vector representing the target gene set.
#' @param gene_sets A list of strings that represent the gene sets to test against.
#' @param gene_universe A character vector representing the gene universe from which the target genes
#' and gene sets are sampled from.
#' 
#' @returns A list with the following elements: 
#' - pvals, the p-values from the hypergeometric test 
#' - odds ratios, the calculated odds ratios
#' - overlap, the size of the overlap,
#' - gene_set_lengths, the length of the gene sets.
#' 
#' @export
rs_hypergeom_test <- function(target_genes, gene_sets, gene_universe) .Call(wrap__rs_hypergeom_test, target_genes, gene_sets, gene_universe)

#' Run a hypergeometric test over a list of target genes
#' 
#' Given a list of target gene sets, this function will test for each of the individual 
#' 
#' @param target_genes A character vector representing the target gene set.
#' @param gene_sets A list of strings that represent the gene sets to test against.
#' @param gene_universe A character vector representing the gene universe from which the target genes
#' and gene sets are sampled from.
#' 
#' @returns A list with the following elements: 
#' - pvals, the p-values from the hypergeometric test 
#' - odds ratios, the calculated odds ratios
#' - overlap, the size of the overlap,
#' - gene_set_lengths, the length of the gene sets.
#' 
#' @export
rs_hypergeom_test_list <- function(target_genes, gene_sets, gene_universe) .Call(wrap__rs_hypergeom_test_list, target_genes, gene_sets, gene_universe)

#' Run hypergeometric enrichment over the gene ontology
#' 
#' This function implements a Rust version of the gene ontology enrichment with elimination:
#' the starting point are the leaves of the ontology and hypergeometric tests will first conducted there.
#' Should the hypergeometric test p-value be below a certain threshold, the genes of that gene ontology
#' term will be removed from all ancestors.
#' 
#' @param target_genes A character vector representing the target gene set.
#' @param go_to_genes A named list with the gene identifers as elements and gene ontology identifiers as 
#' names.
#' @param ancestors A named list with the go identifiers of all ancestors as elements and the gene ontology
#' identifiers as names.
#' @param levels A named list with the go identifiers of that ontology level as elements and the level name
#' as names. IMPORTANT! This list needs to be ordered in the right way!
#' @param gene_universe_length The length of the gene universe.
#' @param min_genes number of minimum genes for the gene ontology term to be tested.
#' @param elim_threshold p-value below which the elimination procedure shall be applied to the ancestors.
#' @param debug boolean that will provide additional console information for debugging purposes.
#' 
#' @returns A list with the following elements: 
#' - go_ids, the gene ontology identifier
#' - pvals, the p-values from the hypergeometric test 
#' - odds ratios, the calculated odds ratios
#' - overlap, the size of the overlap,
#' - gene_set_lengths, the length of the gene sets.
#' 
#' @export
rs_gse_geom_elim <- function(target_genes, go_to_genes, ancestors, levels, gene_universe_length, min_genes, elim_threshold, debug) .Call(wrap__rs_gse_geom_elim, target_genes, go_to_genes, ancestors, levels, gene_universe_length, min_genes, elim_threshold, debug)

#' Run hypergeometric enrichment a list of target genes over the gene ontology
#' 
#' This function implements a Rust version of the gene ontology enrichment with elimination:
#' the starting point are the leaves of the ontology and hypergeometric tests will first conducted there.
#' Should the hypergeometric test p-value be below a certain threshold, the genes of that gene ontology
#' term will be removed from all ancestors. This function is designed to leverage Rust-based threading
#' for parallel processing of a list of target genes.
#' 
#' @param target_genes_list A list of target genes against which to run the method.
#' @param go_to_genes A named list with the gene identifers as elements and gene ontology identifiers as 
#' names.
#' @param ancestors A named list with the go identifiers of all ancestors as elements and the gene ontology
#' identifiers as names.
#' @param levels A named list with the go identifiers of that ontology level as elements and the level name
#' as names. IMPORTANT! This list needs to be ordered in the right way!
#' @param gene_universe_length The length of the gene universe.
#' @param min_genes number of minimum genes for the gene ontology term to be tested.
#' @param elim_threshold: p-value below which the elimination procedure shall be applied to the ancestors.
#' @param debug boolean that will provide additional console information for debugging purposes.
#' 
#' @returns A list with the following elements: 
#' - go_ids, the gene ontology identifier
#' - pvals, the p-values from the hypergeometric test 
#' - odds ratios, the calculated odds ratios
#' - overlap, the size of the overlap,
#' - gene_set_lengths, the length of the gene sets.
#' - no_test, the number of tests that were conducted against target_gene_list. First element indicates
#' how many values belong to the first target_genes set in the list, etc.
#' 
#' @export
rs_gse_geom_elim_list <- function(target_genes_list, go_to_genes, ancestors, levels, gene_universe_length, min_genes, elim_threshold, debug) .Call(wrap__rs_gse_geom_elim_list, target_genes_list, go_to_genes, ancestors, levels, gene_universe_length, min_genes, elim_threshold, debug)

#' Fast AUC calculation
#' 
#' This function calculates rapidly AUCs based on an approximation.
#' 
#' @param pos_scores The scores of your hits.
#' @param neg_scores The scores of your non-hits.
#' @param iters Number of iterations to run the function for. Recommended size: 10,000.
#' @param random_seed Seed.
#' 
#' @export
rs_fast_auc <- function(pos_scores, neg_scores, iters, seed) .Call(wrap__rs_fast_auc, pos_scores, neg_scores, iters, seed)

#' Create random AUCs
#' 
#' This function creates a random set of AUCs based on a score vector and
#' a size of the positive set. This can be used for permutation-based estimation
#' of Z-scores and subsequently p-values.
#' 
#' @param score_vec The overall vector of scores.
#' @param size_pos The size of the hits represented in the score_vec.
#' @param random_iters Number of random AUCs to generate.
#' @param auc_iters Number of random iterations to approximate the AUCs.
#' @param seed Seed.
#' 
#' @export
rs_create_random_aucs <- function(score_vec, size_pos, random_iters, auc_iters, seed) .Call(wrap__rs_create_random_aucs, score_vec, size_pos, random_iters, auc_iters, seed)

#' Generate reciprocal best hits based on set similarities
#' 
#' This function takes a nested list that contains gene modules/sets derived from various methods
#' and generate identifies reciprocal best hits between gene modules/sets across the different origins.
#' 
#' @param module_list A nested named list. The outer list should contain the origin of the gene modules,
#' the inner list the names of the gene modules and the respective genes in them.
#' @param overlap_coefficient Shall the overlap coefficient instead of the Jaccard similarity be used.
#' @param min_similarity Minimum similarity that should exist between any two given gene modules to 
#' actually calculate RBH pairs.
#' @param debug Boolean Boolean that activates print messages for debugging purposes.
#' 
#' @return An R list with 6 elements: 
#' - origin: The name of the origin of the gene modules.
#' - target: The name of the target of the gene modules.
#' - comparisons: Integer vector indicating how many RBH hits were identified in this comparison
#' - origin_modules: Names of the gene modules from the origin.
#' - target_modules: Names of the gene modules from the target.
#' - similarity: The similarities between the two respective gene modules.
#' 
#' @export
rs_rbh_sets <- function(module_list, overlap_coefficient, min_similarity, debug) .Call(wrap__rs_rbh_sets, module_list, overlap_coefficient, min_similarity, debug)


# nolint end
