name: Auto Tag on Version Change
on:
  push:
    branches: [ main ]
    paths: [ 'DESCRIPTION' ]
permissions:
  contents: write
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Extract version from DESCRIPTION
      id: version
      run: |
        VERSION=$(grep "^Version:" DESCRIPTION | sed 's/Version: *//')
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "tag=v$VERSION" >> $GITHUB_OUTPUT
    
    - name: Check if tag exists and create
      uses: rickstaa/action-create-tag@v1
      id: create_tag
      with:
        tag: ${{ steps.version.outputs.tag }}
        tag_exists_error: false
        message: "Release ${{ steps.version.outputs.tag }}"